const RESEND_URL='https://api.resend.com/emails';
const asaasBase=()=>String(process.env.ASAAS_API_URL||'https://api-sandbox.asaas.com/v3').replace(/\/$/,'');
const fail=(message,status=503)=>Object.assign(new Error(message),{status});

export function integrationStatus(){return{resend:{configured:Boolean(process.env.RESEND_API_KEY&&process.env.RESEND_FROM_EMAIL)},asaas:{configured:Boolean(process.env.ASAAS_API_KEY),environment:asaasBase().includes('sandbox')?'sandbox':'production',webhookConfigured:Boolean(process.env.ASAAS_WEBHOOK_TOKEN)},billing:{plan:process.env.CACTUS_PONTO_PLAN_NAME||'STANDARD',price:Number(process.env.CACTUS_PONTO_PLAN_PRICE||0),cycle:'MONTHLY'}}}

export async function sendEmail({to,subject,html,text,idempotencyKey}){const apiKey=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL;if(!apiKey||!from)throw fail('Resend não configurado');const recipients=(Array.isArray(to)?to:[to]).map(x=>String(x||'').trim()).filter(Boolean);if(!recipients.length)throw fail('Destinatário de e-mail inválido',400);const headers={Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'};if(idempotencyKey)headers['Idempotency-Key']=String(idempotencyKey);const r=await fetch(RESEND_URL,{method:'POST',headers,body:JSON.stringify({from,to:recipients,subject:String(subject||'Cactus Ponto'),html,text})});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{data={message:raw}}if(!r.ok)throw fail(`Falha no envio de e-mail (${r.status})`,502);return data}

export async function asaasRequest(path,{method='GET',body}={}){const apiKey=process.env.ASAAS_API_KEY;if(!apiKey)throw fail('Asaas não configurado');const r=await fetch(`${asaasBase()}${path}`,{method,headers:{'Content-Type':'application/json','User-Agent':'Cactus-Ponto/0.28.0','access_token':apiKey},body:body===undefined?undefined:JSON.stringify(body)});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{data={message:raw}}if(!r.ok){const detail=Array.isArray(data?.errors)?data.errors.map(x=>x.description||x.code).filter(Boolean).join('; '):data?.message;throw fail(`Falha na integração Asaas (${r.status})${detail?`: ${String(detail).slice(0,240)}`:''}`,502)}return data}

export function billingTransition(event){if(['PAYMENT_RECEIVED','PAYMENT_CONFIRMED'].includes(event))return{status:'ACTIVE',tenantActive:true};if(event==='PAYMENT_OVERDUE')return{status:'PAST_DUE',tenantActive:process.env.BILLING_SUSPEND_ON_OVERDUE==='false'?null:false};if(['PAYMENT_REFUNDED','PAYMENT_DELETED','PAYMENT_CHARGEBACK_REQUESTED'].includes(event))return{status:'SUSPENDED',tenantActive:false};if(event==='PAYMENT_CREATED')return{status:'PENDING',tenantActive:null};return null}
