import{Router}from'express';
import{query}from'./db.js';
import{isUuid}from'./id-validation.js';
import{sendEmail,asaasRequest,integrationStatus,billingTransition}from'./integrations.js';
import{domainConfig,listTenantDomains,primaryTenantDomain,ensureDefaultTenantDomain,createCustomDomain,verifyCustomDomain,makePrimaryDomain,deleteCustomDomain,publicDomainUrl}from'./tenant-domains.js';
const router=Router(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),tomorrow=()=>new Date(Date.now()+86400000).toISOString().slice(0,10);
async function billingPatch(tenantId,patch,tenantActive=null){const r=await query(`UPDATE tenants SET settings=jsonb_set(coalesce(settings,'{}'::jsonb),'{billing}',coalesce(settings->'billing','{}'::jsonb)||$2::jsonb,true),active=coalesce($3::boolean,active) WHERE id=$1 RETURNING active,settings`,[tenantId,JSON.stringify({...patch,updatedAt:new Date().toISOString()}),tenantActive]);return r.rows[0]}
async function tenantBilling(tenantId){const r=await query(`SELECT id,name,trade_name,cnpj,active,coalesce(settings,'{}'::jsonb)settings FROM tenants WHERE id=$1`,[tenantId]);return r.rows[0]}
export function settingsRoutes(auth){
router.get('/settings',auth(['ADMIN','HR']),async(req,res,next)=>{try{const[t,h]=await Promise.all([query(`SELECT id,name,trade_name,cnpj,timezone,coalesce(settings,'{}'::jsonb)settings FROM tenants WHERE id=$1`,[req.user.tenantId]),query(`SELECT * FROM holidays WHERE tenant_id=$1 ORDER BY holiday_date`,[req.user.tenantId])]);res.json({...t.rows[0],holidays:h.rows})}catch(e){next(e)}});
router.put('/settings',auth(['ADMIN','HR']),async(req,res,next)=>{try{const{timezone,settings={}}=req.body,r=await query(`UPDATE tenants SET timezone=coalesce($2,timezone),settings=coalesce(settings,'{}'::jsonb)||$3::jsonb WHERE id=$1 RETURNING timezone,settings`,[req.user.tenantId,timezone||null,JSON.stringify(settings)]);res.json(r.rows[0])}catch(e){next(e)}});
router.post('/holidays',auth(['ADMIN','HR']),async(req,res,next)=>{try{const{name,date}=req.body;if(!name||!date)return res.status(400).json({error:'Nome e data são obrigatórios'});const r=await query(`INSERT INTO holidays(tenant_id,name,holiday_date)VALUES($1,$2,$3) ON CONFLICT(tenant_id,holiday_date)DO UPDATE SET name=$2 RETURNING *`,[req.user.tenantId,name,date]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
router.delete('/holidays/:id',auth(['ADMIN','HR']),async(req,res,next)=>{try{if(!isUuid(req.params.id))return res.status(400).json({error:'Feriado inválido'});await query(`DELETE FROM holidays WHERE tenant_id=$1 AND id=$2`,[req.user.tenantId,req.params.id]);res.status(204).end()}catch(e){next(e)}});
router.get('/tenant/domains',auth(['ADMIN']),async(req,res,next)=>{try{res.json({...domainConfig(),domains:await listTenantDomains(req.user.tenantId)})}catch(e){next(e)}});
router.post('/tenant/domains/default',auth(['ADMIN']),async(req,res,next)=>{try{const t=await tenantBilling(req.user.tenantId),d=await ensureDefaultTenantDomain(req.user.tenantId,t.trade_name||t.name,req.body?.slug);res.status(201).json({domain:d,url:publicDomainUrl(d.domain),...domainConfig()})}catch(e){next(e)}});
router.post('/tenant/domains/custom',auth(['ADMIN']),async(req,res,next)=>{try{const d=await createCustomDomain(req.user.tenantId,req.body?.domain);res.status(201).json({domain:d,...domainConfig(),instruction:`Crie um CNAME de ${d.domain} para ${domainConfig().cnameTarget}`})}catch(e){next(e)}});
router.post('/tenant/domains/:id/verify',auth(['ADMIN']),async(req,res,next)=>{try{if(!isUuid(req.params.id))return res.status(400).json({error:'Domínio inválido'});const x=await verifyCustomDomain(req.user.tenantId,req.params.id);if(!x.verified)return res.status(409).json({error:`CNAME ainda não aponta para ${x.cnameTarget}`,...x});res.json(x)}catch(e){next(e)}});
router.put('/tenant/domains/:id/primary',auth(['ADMIN']),async(req,res,next)=>{try{if(!isUuid(req.params.id))return res.status(400).json({error:'Domínio inválido'});const d=await makePrimaryDomain(req.user.tenantId,req.params.id);res.json({domain:d,url:publicDomainUrl(d.domain)})}catch(e){next(e)}});
router.delete('/tenant/domains/:id',auth(['ADMIN']),async(req,res,next)=>{try{if(!isUuid(req.params.id))return res.status(400).json({error:'Domínio inválido'});await deleteCustomDomain(req.user.tenantId,req.params.id);res.status(204).end()}catch(e){next(e)}});
router.get('/integrations/status',auth(['ADMIN']),async(req,res)=>res.json(integrationStatus()));
router.post('/integrations/email/test',auth(['ADMIN']),async(req,res,next)=>{try{const to=String(req.body?.to||req.user.email||'').trim();const x=await sendEmail({to,subject:'Cactus Ponto · teste de e-mail',html:`<h2>Cactus Ponto 🌵</h2><p>Olá, ${esc(req.user.name)}.</p><p>A integração com o Resend está funcionando corretamente.</p>`,text:`Cactus Ponto - integração Resend funcionando para ${req.user.name}.`,idempotencyKey:`cactus-ponto-email-test/${req.user.id}/${new Date().toISOString().slice(0,13)}`});res.json({ok:true,id:x.id||null,to})}catch(e){next(e)}});
router.get('/billing/status',auth(['ADMIN']),async(req,res,next)=>{try{const t=await tenantBilling(req.user.tenantId),d=await primaryTenantDomain(req.user.tenantId);res.json({tenantActive:t.active,billing:t.settings?.billing||{},integration:integrationStatus().asaas,plan:integrationStatus().billing,accessDomain:d?{...d,url:publicDomainUrl(d.domain)}:null})}catch(e){next(e)}});
router.post('/billing/customer',auth(['ADMIN']),async(req,res,next)=>{try{const t=await tenantBilling(req.user.tenantId),name=String(req.body?.name||t.trade_name||t.name||'').trim(),cpfCnpj=String(req.body?.cpfCnpj||t.cnpj||'').replace(/\D/g,''),email=String(req.body?.email||req.user.email||'').trim().toLowerCase(),mobilePhone=String(req.body?.mobilePhone||'').replace(/\D/g,'');if(!name||![11,14].includes(cpfCnpj.length)||!email)return res.status(400).json({error:'Nome, CPF/CNPJ e e-mail válidos são obrigatórios'});const customer=await asaasRequest('/customers',{method:'POST',body:{name,cpfCnpj,email,...(mobilePhone?{mobilePhone}:{})}});const saved=await billingPatch(req.user.tenantId,{asaasCustomerId:customer.id,status:'SETUP'});res.status(201).json({customerId:customer.id,billing:saved.settings.billing})}catch(e){next(e)}});
router.post('/billing/subscription',auth(['ADMIN']),async(req,res,next)=>{try{const t=await tenantBilling(req.user.tenantId),billing=t.settings?.billing||{},price=Number(process.env.CACTUS_PONTO_PLAN_PRICE||0),plan=process.env.CACTUS_PONTO_PLAN_NAME||'STANDARD',billingType=String(req.body?.billingType||'PIX').toUpperCase();if(!billing.asaasCustomerId)return res.status(409).json({error:'Cadastre o cliente de cobrança antes de criar a assinatura'});if(!Number.isFinite(price)||price<=0)return res.status(503).json({error:'Preço do plano ainda não foi configurado no servidor'});if(!['PIX','BOLETO'].includes(billingType))return res.status(400).json({error:'Forma de pagamento disponível nesta etapa: PIX ou BOLETO'});const subscription=await asaasRequest('/subscriptions',{method:'POST',body:{customer:billing.asaasCustomerId,billingType,nextDueDate:tomorrow(),value:price,cycle:'MONTHLY',description:`Cactus Ponto · Plano ${plan}`}});let payments={data:[]};try{payments=await asaasRequest(`/subscriptions/${subscription.id}/payments?limit=1&offset=0`)}catch{}const first=payments?.data?.[0]||null,saved=await billingPatch(req.user.tenantId,{asaasSubscriptionId:subscription.id,status:'PENDING',plan,price,billingType,lastPaymentId:first?.id||null,invoiceUrl:first?.invoiceUrl||first?.bankSlipUrl||null});if(req.user.email)sendEmail({to:req.user.email,subject:'Cactus Ponto · assinatura criada',html:`<h2>Assinatura criada 🌵</h2><p>Plano <b>${esc(plan)}</b> configurado por R$ ${price.toFixed(2).replace('.',',')}/mês.</p>${first?.invoiceUrl?`<p><a href="${esc(first.invoiceUrl)}">Abrir cobrança no Asaas</a></p>`:''}`,text:`Cactus Ponto: assinatura ${plan} criada.`,idempotencyKey:`cactus-ponto-subscription/${subscription.id}`}).catch(()=>{});res.status(201).json({subscriptionId:subscription.id,status:'PENDING',plan,price,billingType,payment:first?{id:first.id,status:first.status,invoiceUrl:first.invoiceUrl||null,bankSlipUrl:first.bankSlipUrl||null,dueDate:first.dueDate||null}:null,billing:saved.settings.billing})}catch(e){next(e)}});
router.post('/billing/webhook/asaas',async(req,res,next)=>{try{const expected=String(process.env.ASAAS_WEBHOOK_TOKEN||''),received=String(req.get('asaas-access-token')||'');if(!expected)return res.status(503).json({error:'Webhook Asaas não configurado'});if(received!==expected)return res.status(401).json({error:'Webhook não autorizado'});const eventId=String(req.body?.id||''),event=String(req.body?.event||''),payment=req.body?.payment||{},subscriptionId=String(payment.subscription||'');if(!eventId||!event||!subscriptionId)return res.status(200).json({ok:true,ignored:true});const t=await query(`SELECT id,name,trade_name,settings FROM tenants WHERE settings->'billing'->>'asaasSubscriptionId'=$1 LIMIT 1`,[subscriptionId]);if(!t.rowCount)return res.status(200).json({ok:true,ignored:true});const tenant=t.rows[0],dup=await query(`SELECT 1 FROM audit_logs WHERE tenant_id=$1 AND action='ASAAS_WEBHOOK' AND metadata->>'eventId'=$2 LIMIT 1`,[tenant.id,eventId]);if(dup.rowCount)return res.status(200).json({ok:true,duplicate:true});const transition=billingTransition(event),patch={lastWebhookEvent:event,lastWebhookEventId:eventId,lastPaymentId:payment.id||null,invoiceUrl:payment.invoiceUrl||payment.bankSlipUrl||tenant.settings?.billing?.invoiceUrl||null};if(transition)Object.assign(patch,{status:transition.status});await billingPatch(tenant.id,patch,transition?.tenantActive??null);let accessDomain=null;if(transition?.status==='ACTIVE')accessDomain=await ensureDefaultTenantDomain(tenant.id,tenant.trade_name||tenant.name);await query(`INSERT INTO audit_logs(tenant_id,action,entity_type,metadata)VALUES($1,'ASAAS_WEBHOOK','tenant',$2)`,[tenant.id,{eventId,event,paymentId:payment.id||null,subscriptionId,accessDomain:accessDomain?.domain||null}]);const admin=await query(`SELECT email,name FROM users WHERE tenant_id=$1 AND role='ADMIN' AND active ORDER BY created_at LIMIT 1`,[tenant.id]);res.status(200).json({ok:true,accessDomain:accessDomain?.domain||null});if(admin.rowCount&&transition){const loginUrl=accessDomain?publicDomainUrl(accessDomain.domain):null;sendEmail({to:admin.rows[0].email,subject:`Cactus Ponto · cobrança ${transition.status}`,html:`<h2>Cactus Ponto 🌵</h2><p>Olá, ${esc(admin.rows[0].name)}.</p><p>Status da assinatura: <b>${esc(transition.status)}</b>.</p>${loginUrl?`<p>Seu endereço de acesso é <a href="${esc(loginUrl)}">${esc(loginUrl)}</a>.</p>`:''}${patch.invoiceUrl?`<p><a href="${esc(patch.invoiceUrl)}">Abrir cobrança</a></p>`:''}`,text:`Cactus Ponto: status da assinatura ${transition.status}.${loginUrl?` Acesse em ${loginUrl}.`:''}`,idempotencyKey:`cactus-ponto-billing/${eventId}`}).catch(()=>{})}}catch(e){next(e)}});
return router}
