import crypto from'crypto';
import{resolveCname}from'node:dns/promises';
import{query}from'./db.js';

export const normalizeDomain=value=>{let v=String(value||'').trim().toLowerCase();if(!v)return'';try{if(v.includes('://'))v=new URL(v).hostname;else v=v.split('/')[0].split(':')[0]}catch{}return v.replace(/\.$/,'')};
export const slugify=value=>String(value||'empresa').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)||'empresa';
export const validDomain=domain=>{const d=normalizeDomain(domain);return d.length<=253&&d.includes('.')&&!/^\d+(?:\.\d+){3}$/.test(d)&&d.split('.').every(x=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(x))};
const baseDomain=()=>normalizeDomain(process.env.CACTUS_PONTO_BASE_DOMAIN||'ponto.cactustecnologia.com.br');
const cnameTarget=()=>normalizeDomain(process.env.CACTUS_PONTO_CUSTOM_CNAME||`custom.${baseDomain()}`);
const scheme=()=>String(process.env.CACTUS_PONTO_PUBLIC_SCHEME||'https').replace(/:.*$/,'')||'https';
export const domainConfig=()=>({baseDomain:baseDomain(),cnameTarget:cnameTarget(),scheme:scheme()});
export const publicDomainUrl=domain=>`${scheme()}://${normalizeDomain(domain)}`;
export const customDomainMatches=(records,target=cnameTarget())=>(records||[]).map(normalizeDomain).includes(normalizeDomain(target));

export async function listTenantDomains(tenantId){const r=await query(`SELECT id,domain,type,verified,is_primary,verified_at,created_at FROM tenant_domains WHERE tenant_id=$1 ORDER BY is_primary DESC,type,created_at`,[tenantId]);return r.rows}
export async function primaryTenantDomain(tenantId){const r=await query(`SELECT id,domain,type,verified,is_primary,verified_at,created_at FROM tenant_domains WHERE tenant_id=$1 AND verified ORDER BY is_primary DESC,(type='CACTUS') DESC,created_at LIMIT 1`,[tenantId]);return r.rows[0]||null}
export async function ensureDefaultTenantDomain(tenantId,name,preferredSlug){const existing=await query(`SELECT * FROM tenant_domains WHERE tenant_id=$1 AND type='CACTUS' ORDER BY created_at LIMIT 1`,[tenantId]);if(existing.rowCount)return existing.rows[0];const base=baseDomain(),root=slugify(preferredSlug||name);for(let i=0;i<50;i++){const suffix=i?`-${i+1}`:'',slug=(root.slice(0,48-suffix.length)+suffix),domain=`${slug}.${base}`;const r=await query(`INSERT INTO tenant_domains(tenant_id,domain,type,verified,is_primary,verified_at) VALUES($1,$2,'CACTUS',true,NOT EXISTS(SELECT 1 FROM tenant_domains WHERE tenant_id=$1 AND is_primary),now()) ON CONFLICT DO NOTHING RETURNING *`,[tenantId,domain]);if(r.rowCount)return r.rows[0]}throw Object.assign(new Error('Não foi possível reservar um subdomínio Cactus para a empresa'),{status:409})}
export async function createCustomDomain(tenantId,value){const domain=normalizeDomain(value),base=baseDomain();if(!validDomain(domain)||domain===base||domain.endsWith(`.${base}`))throw Object.assign(new Error('Domínio personalizado inválido'),{status:400});const token=crypto.randomBytes(16).toString('hex');try{const r=await query(`INSERT INTO tenant_domains(tenant_id,domain,type,verified,is_primary,verification_token) VALUES($1,$2,'CUSTOM',false,false,$3) RETURNING id,domain,type,verified,is_primary,verified_at,created_at`,[tenantId,domain,token]);return r.rows[0]}catch(e){if(e.code==='23505')throw Object.assign(new Error('Este domínio já está vinculado a uma empresa'),{status:409});throw e}}
export async function verifyCustomDomain(tenantId,id){const r=await query(`SELECT * FROM tenant_domains WHERE tenant_id=$1 AND id=$2 AND type='CUSTOM'`,[tenantId,id]);if(!r.rowCount)throw Object.assign(new Error('Domínio não encontrado'),{status:404});const row=r.rows[0];let records=[];try{records=await resolveCname(row.domain)}catch{}if(!customDomainMatches(records))return{verified:false,domain:row.domain,cnameTarget:cnameTarget(),records};const u=await query(`UPDATE tenant_domains SET verified=true,verified_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,domain,type,verified,is_primary,verified_at,created_at`,[tenantId,id]);return{verified:true,domain:u.rows[0],cnameTarget:cnameTarget(),records}}
export async function makePrimaryDomain(tenantId,id){const r=await query(`WITH candidate AS(SELECT id FROM tenant_domains WHERE tenant_id=$1 AND id=$2 AND verified),cleared AS(UPDATE tenant_domains SET is_primary=false WHERE tenant_id=$1 AND EXISTS(SELECT 1 FROM candidate)) UPDATE tenant_domains SET is_primary=true WHERE tenant_id=$1 AND id IN(SELECT id FROM candidate) RETURNING id,domain,type,verified,is_primary,verified_at,created_at`,[tenantId,id]);if(!r.rowCount)throw Object.assign(new Error('Domínio verificado não encontrado'),{status:404});return r.rows[0]}
export async function deleteCustomDomain(tenantId,id){const r=await query(`DELETE FROM tenant_domains WHERE tenant_id=$1 AND id=$2 AND type='CUSTOM' AND is_primary=false RETURNING id`,[tenantId,id]);if(!r.rowCount)throw Object.assign(new Error('Domínio não encontrado ou é o domínio principal'),{status:409});return true}
export async function tenantHostMiddleware(req,res,next){try{const host=normalizeDomain(req.hostname||req.headers.host||'');if(!host||host==='localhost'||host==='127.0.0.1'||host==='::1')return next();const r=await query(`SELECT tenant_id,domain,verified,is_primary FROM tenant_domains WHERE lower(domain)=lower($1) LIMIT 1`,[host]);if(!r.rowCount)return next();const d=r.rows[0];if(!d.verified)return res.status(421).json({error:'Domínio da empresa ainda não foi verificado'});req.hostTenantId=d.tenant_id;req.tenantDomain=d;next()}catch(e){next(e)}}
